language: node_js
node_js:
- '0.6'
- '0.8'
- '0.9'
- '0.10'
- '0.11'
env:
  global:
  - secure: kLA4BjtaAuVB9QHPOuei+zyxkKAPKQozHLWAf6FVHe6fnEnO5lJOOrMk/DRfDuyVDun8UwLxUs+7a1FOIUf8EUYm2VonIOr0FSZXzUOU2eGBSTNfhAN0urZkitZYeTuMslnLuS1Rc7RHT7ZcmEyJVhRaSmbza0wv9PBy0Rpmof0=
  - secure: eCwA806b4si1qQzL0cAIsMLqSZ+USbmi1l2Pkxl1x/74EF3KhnmooZxOBkPhzslqsJ3o5JKgDsrg/+TsM0nHSjYcokbuUTkRxde66dDFMwNGxAMnwpMGQvtBkuBSLulk+ZuHsEB+5QrPO4igK9FF9cGlenx7dmc5uVUtqvcho68=
  - secure: HRfD9bHqlxjwAZEHkOGH/f9XNsCqVQKxPl4bxDwoJ8RT9QbkEwVTNwkvehJ4YWlu8j9h5s3WWlzeahpnRm4VObsrwF/n6S5Q3ODSUZy8Rm2TGy/V6HHTsYTcjJRRbPexS40Pe1/pkFiTP0iDCulUDxa7GC6nDgeRF15V/YcbEXo=
  - secure: aEwHFk+aKt0zQndZk4gX/oVCx0NDA05ybzlumqVmHKanyKQqGs3w4gbjxIyUja+zsAzrnNjr0sdYwGIrP7wJT9IFfdKCY9g7SZuPLNBD+hgFtrc4Ws8ktyV/PDiRWyAgYuhVbB2s3t5EhF5ntPEsrPpKZ82bbgwOaao8Px1JSlk=
